// Seed data — used by server.js bootstrap to auto-seed on first boot
export default {
  projects: [
    {
      missionId: 'MISSION-001',
      title: 'SkillBridge',
      tagline: 'A marketplace where skills meet opportunities.',
      description:
        'A full-stack marketplace where mentors and learners connect. Realtime chat, secure payments, scheduling, and a recommendation engine based on skill graphs. Built end-to-end on the MERN stack with JWT auth, Socket.IO realtime, and Stripe payments.',
      stack: ['MongoDB', 'Express', 'React', 'Node', 'Socket.IO', 'Stripe'],
      status: 'Active',
      difficulty: 'High',
      githubUrl: 'https://github.com/tosifraza/skillbridge',
      liveUrl: 'https://skillbridge.demo.founderos.dev',
      featured: true,
      order: 1,
    },
    {
      missionId: 'MISSION-002',
      title: 'DevPulse Dashboard',
      tagline: 'Analytics dashboard built for indie developers.',
      description:
        'A privacy-first analytics platform that indie developers can drop into any site. Features realtime visitor maps, funnel analysis, custom events, and a sleek glassmorphism UI. Uses Mongoose aggregation pipelines for fast queries.',
      stack: ['MongoDB', 'Express', 'React', 'Node', 'Tailwind', 'Framer Motion'],
      status: 'Active',
      difficulty: 'Medium',
      githubUrl: 'https://github.com/tosifraza/devpulse',
      liveUrl: 'https://devpulse.demo.founderos.dev',
      featured: true,
      order: 2,
    },
    {
      missionId: 'MISSION-003',
      title: 'MERN Auth Toolkit',
      tagline: 'Production-ready auth boilerplate for MERN apps.',
      description:
        'An open-source JWT auth toolkit with refresh tokens, email verification, password reset, role-based access control, and a polished React UI. Used as the foundation for every project in this portfolio.',
      stack: ['MongoDB', 'Express', 'React', 'Node', 'JWT', 'Nodemailer'],
      status: 'Completed',
      difficulty: 'Medium',
      githubUrl: 'https://github.com/tosifraza/mern-auth-toolkit',
      liveUrl: '',
      featured: false,
      order: 3,
    },
    {
      missionId: 'MISSION-004',
      title: 'Founder OS',
      tagline: 'The portfolio you are looking at right now.',
      description:
        'A futuristic, OS-themed personal portfolio with three independent apps: public Frontend, Admin Portal CMS, and an Express + MongoDB backend. Boot animation, glassmorphism panels, AI recruiter assistant, and a Mission Control project view.',
      stack: ['MongoDB', 'Express', 'React', 'Node', 'Framer Motion', 'Tailwind'],
      status: 'Active',
      difficulty: 'Extreme',
      githubUrl: 'https://github.com/tosifraza/founder-os',
      liveUrl: 'https://founderos.dev',
      featured: true,
      order: 4,
    },
    {
      missionId: 'MISSION-005',
      title: 'Inkwell — AI Story Companion',
      tagline: 'AI-assisted writing tool for novelists.',
      description:
        'An AI-assisted writing environment with character tracking, plot threads, and tone-aware completions. Backend uses streaming LLM responses over Server-Sent Events for a buttery writing experience.',
      stack: ['MongoDB', 'Express', 'React', 'Node', 'SSE', 'Tailwind'],
      status: 'In Progress',
      difficulty: 'High',
      githubUrl: 'https://github.com/tosifraza/inkwell',
      liveUrl: '',
      featured: false,
      order: 5,
    },
    {
      missionId: 'MISSION-006',
      title: 'PulseTrade',
      tagline: 'Crypto portfolio tracker with realtime prices.',
      description:
        'A realtime crypto portfolio tracker with price alerts, transaction history, and beautiful charts. WebSocket price feed, Mongoose time-series collections, and a buttery-smooth React UI.',
      stack: ['MongoDB', 'Express', 'React', 'Node', 'WebSocket', 'Chart.js'],
      status: 'Archived',
      difficulty: 'High',
      githubUrl: 'https://github.com/tosifraza/pulsetrade',
      liveUrl: '',
      featured: false,
      order: 6,
    },
  ],
  skills: [
    { name: 'HTML5', category: 'Frontend', level: 95, order: 1 },
    { name: 'CSS3', category: 'Frontend', level: 90, order: 2 },
    { name: 'JavaScript', category: 'Frontend', level: 92, order: 3 },
    { name: 'React', category: 'Frontend', level: 90, order: 4 },
    { name: 'Redux', category: 'Frontend', level: 82, order: 5 },
    { name: 'Tailwind CSS', category: 'Frontend', level: 95, order: 6 },
    { name: 'Framer Motion', category: 'Frontend', level: 80, order: 7 },
    { name: 'Node.js', category: 'Backend', level: 88, order: 1 },
    { name: 'Express.js', category: 'Backend', level: 90, order: 2 },
    { name: 'REST APIs', category: 'Backend', level: 92, order: 3 },
    { name: 'JWT Auth', category: 'Backend', level: 88, order: 4 },
    { name: 'Socket.IO', category: 'Backend', level: 75, order: 5 },
    { name: 'MongoDB', category: 'Database', level: 88, order: 1 },
    { name: 'Mongoose', category: 'Database', level: 90, order: 2 },
    { name: 'Redis', category: 'Database', level: 65, order: 3 },
    { name: 'Git', category: 'Tools', level: 90, order: 1 },
    { name: 'GitHub', category: 'Tools', level: 92, order: 2 },
    { name: 'Postman', category: 'Tools', level: 92, order: 3 },
    { name: 'VS Code', category: 'Tools', level: 95, order: 4 },
    { name: 'Vite', category: 'Tools', level: 85, order: 5 },
    { name: 'Docker', category: 'DevOps', level: 65, order: 1 },
    { name: 'Nginx', category: 'DevOps', level: 60, order: 2 },
    { name: 'CI/CD', category: 'DevOps', level: 70, order: 3 },
  ],
  timeline: [
    { title: 'Started Learning Programming', year: '2019', phase: 'learning', description: 'First "Hello World" in Python. Fell in love with the craft of building things from nothing but text.', icon: '🌱', order: 1 },
    { title: 'Computer Science Student', year: '2020', phase: 'student', description: 'Formal CS education. Data structures, algorithms, operating systems, databases. Built a foundation that everything else stands on.', icon: '🎓', order: 2 },
    { title: 'MERN Stack Developer', year: '2022', phase: 'developer', description: 'Specialised in MongoDB, Express, React, Node. Shipped 6+ full-stack applications. First paid freelance client.', icon: '💻', order: 3 },
    { title: 'Product Builder', year: '2024', phase: 'builder', description: 'Started building products end-to-end — from idea to deployed. Launched SkillBridge, DevPulse, and Founder OS.', icon: '🚀', order: 4 },
    { title: 'Future Founder', year: '2026', phase: 'founder', description: 'Currently architecting a SaaS product. Building in public. Raising a pre-seed round. The next chapter starts now.', icon: '⭐', order: 5 },
  ],
  achievements: [
    { title: '1,000+ GitHub Stars', description: 'Cumulative stars across open-source projects.', issuer: 'GitHub', date: '2024', icon: '⭐', color: '#f59e0b', order: 1 },
    { title: 'Top 5% Developer', description: 'Ranked in the top 5% of contributors on a major MERN project.', issuer: 'Open Source Community', date: '2024', icon: '🏆', color: '#a855f7', order: 2 },
    { title: 'Shipped 6+ Products', description: 'Built and deployed six full-stack MERN products to production.', issuer: 'Self', date: '2024', icon: '🚀', color: '#00d4ff', order: 3 },
    { title: 'Hackathon Winner', description: 'First place at a national-level 24-hour hackathon.', issuer: 'Hackathon India', date: '2023', icon: '🥇', color: '#10b981', order: 4 },
    { title: 'Speaker — React Meetup', description: 'Delivered a talk on building reusable component systems with React + Tailwind.', issuer: 'React India', date: '2024', icon: '🎤', color: '#14b8a6', order: 5 },
    { title: 'Mentor — Code for India', description: 'Mentored 15+ junior developers on MERN stack best practices.', issuer: 'Code for India', date: '2024', icon: '🧭', color: '#22c55e', order: 6 },
  ],
};
